### ISSUE TITLE
Update menu for website

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/kestra.io#286]
### Issue description

Right now the "Company" component takes too much place in the menu for a low visitor income.

Can you make the change on the menu to have a direct entry to replace the dropdown for "Company". We keep the company in the footer but not in the Menu.

New menu entries:
Product (Dropdown menu)
Solution (Dropdown menu)
Docs (Dropdown menu)
Community (Direct Entry) (no more dropdown with blogs in it)
Blogs (Direct Entry)

**Comment by tchiotludo** [comment]
done in https://github.com/kestra-io/kestra.io/commit/0b5d6d036169fc1d4345c6e90f5b059ad2b4123a
