### ISSUE TITLE
Fix numbers or cut the section from the website

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra.io#313]
### Expected Behavior

These numbers seem to be too high:
![image](https://github.com/kestra-io/kestra.io/assets/86264395/b6f66106-8f4e-4631-82c3-2dd3048c2dbb)

Do these numbers summarize all issues/PRs and stars across all repositories? If so, is it intentional?

### Environment Information

main page on the website kestra.io

**Comment by tchiotludo** [comment]
Yes it's number across all repositories. Yes we have more contribution on plugins than core, so it's mostly to balanced others mono repositories that will have a lot of contributions on docs and plugins.

But I agree it can be surprising

**Comment by anna-geller** [comment]
I see, this is a good point. Plugins are indeed an easier way to contribute and only showing the main repo would also exclude e.g. contributions to docs, so let me close the issue then 👍 thanks for explaining
