### ISSUE TITLE
Some errors in Getting Started page?

### ISSUE THREAD

**Issue by fdelbrayelle** [kestra-io/kestra.io#34]
### Expected Behavior

I've noticed that when following the guide in [getting started](https://kestra.io/docs/getting-started/) I already have some existing flows unlike what it's written on the page ("The default installation is empty and don't contain any flows."):

![image](https://user-images.githubusercontent.com/296836/161393397-790c3f5b-e532-436f-ab5f-dd2cf006d159.png)

In addition, the "Overview" tab seems not to exist so maybe this sentence ("You will see the Topology of your flow as graph on Overview tabs.") should be replaced:

![image](https://user-images.githubusercontent.com/296836/161395560-4a7dc57b-a9b8-46a2-9a62-57427e6153d8.png)

### Actual Behaviour

Maybe write there is actually some flows unless it's an abnormal behaviour?

### Steps To Reproduce

The steps on https://kestra.io/docs/getting-started

### Environment Information

- Kestra Version: latest
- Operating System (OS / Docker / Kubernetes): Ubuntu
- Java Version (If not docker): 11

**Comment by tchiotludo** [comment]
THanks for the report :smile: 
In fact, before there is no flow by default and I added some recently, I correct the docs. 

For the Overview tabs, this is only exist on the Enterprise edition :smile:
