### ISSUE TITLE
Feedback "Declarative Data Orchestration with Kestra"

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra.io#350]
### Expected Behavior

- The background glow should be below 3 features. <img width="1181" alt="Capture d’écran 2023-07-10 à 14 26 05" src="https://github.com/kestra-io/kestra.io/assets/125994028/d28f8aae-b6b8-436b-91a0-f642a62b6528">
- Can you change hero artwork with [this new export](https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=1848%3A11934&mode=design&t=sAU5iasNhu1au4fg-1) <img width="570" alt="Capture d’écran 2023-07-10 à 14 38 44" src="https://github.com/kestra-io/kestra.io/assets/125994028/2d1afa01-aee5-4dcf-860e-5c2b77fcd943">

Thanks

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by tchiotludo** [comment]
please provide an svg image, the png is largely too big (1.6mo vs 76ko)

**Comment by Nico-Kestra** [comment]
You can export it [here](https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=2049%3A11057&mode=design&t=CgBrhFFzO954uIa6-1)
