### ISSUE TITLE
Change labels menu header

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra.io#398]
### Feature description

In this order : 
- Product
  - Features
  - Enterprise Edition
  - Declarative Orchestration
- Use cases
  - Usages & Use cases
  - CI/CD for your Kestra Workflows
  - Modern Data Stack Integration
  - Change Data Capture
- Documentation
- [Plugins](https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=3288%3A26508&mode=design&t=4c9CqrAGZscNAXHu-1)
- Blog
- Resources
  - About us
  - Community
  - Careers
  - Contact us

[Figma](https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=249%3A372&mode=design&t=4c9CqrAGZscNAXHu-1)

**Comment by anna-geller** [comment]
looks great, it could be slightly renamed too:

- Product
  - Open Source
  - Enterprise Edition
  - Declarative Orchestration
- Solutions
  - Use cases
  - CI/CD for Kestra Workflows
  - Modern Data Stack Integration
  - Change Data Capture
- Docs
- [Plugins](https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=3288%3A26508&mode=design&t=4c9CqrAGZscNAXHu-1)
- Blog
- Resources
  - Community
  - About us
  - Careers
  - Contact us

**Comment by tchiotludo** [comment]
done in https://github.com/kestra-io/kestra.io/commit/0b5d6d036169fc1d4345c6e90f5b059ad2b4123a
