### ISSUE TITLE
Add a picto to a menu entry

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/kestra.io#421]
### Issue description

Hey! would like to add a picture to a menu entry added:
Kestra VS Airflow =>
![VS-picto](https://github.com/kestra-io/kestra.io/assets/125883179/43ad491c-4556-4ca1-9dfc-87ce4d0a0236)

at this place: 
<img width="269" alt="image" src="https://github.com/kestra-io/kestra.io/assets/125883179/8807c47f-9ba1-4c06-876a-b9a3eb00f008">

Also would love to have your insights to have autonomy for Menu updates!

**Comment by tchiotludo** [comment]
done in 1801c48b40df400f42bd0d6ff57e8bbcc7c778c2
