### ISSUE TITLE
Documentation about docker executor for python & bash

### ISSUE THREAD

**Issue by owaismultani** [kestra-io/kestra.io#85]
### Actual Behaviour

![image](https://user-images.githubusercontent.com/47238206/154907933-53ab3dd7-88ec-4d90-848a-86faefcbaea5.png)

Possible issue: python used is python3 and no alias is set for python, hence the error.

### Steps To Reproduce

Getting Error Running given example. It says Python is not found.
1. Run docker container
2. Go to http://localhost:8080/
2. Go to Flows
3. Create a new flow with the following:

```
id: pythonTest
namespace: io.kestra.test
revision: 1
tasks:

id: Test001
type: io.kestra.core.tasks.scripts.Python
args:

data.json
inputFiles:
data.json: |
{"status": "OK"}
main.py: |
from kestra import Kestra
import json
import requests
import sys
result = json.loads(open(sys.argv[1]).read())
print(f"python script {result['status']}")
response = requests.get('http://google.com/')
print(response.status_code)
Kestra.outputs({'status': response.status_code, 'text': response.text})
pip.conf: |
# some specific pip repository configuration
requirements:

|-
requests
Copied!
```

reference: (https://kestra.io/plugins/core/tasks/scripts/io.kestra.core.tasks.scripts.Python.html)

### Environment Information

- Kestra Version: develop-full
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

```
id: pythonTest
namespace: io.kestra.test
revision: 1
tasks:
  - id: Test001
    type: io.kestra.core.tasks.scripts.Python
    args:
      - data.json
    inputFiles:
      data.json: |
        {"status": "OK"}
      main.py: |
        from kestra import Kestra
        import json
        import requests
        import sys
        result = json.loads(open(sys.argv[1]).read())
        print(f"python script {result['status']}")
        response = requests.get('http://google.com')
        print(response.status_code)
        Kestra.outputs({'status': response.status_code, 'text': response.text})
      pip.conf: |
        # some specific pip repository configuration

    requirements:
      - |-
        requests
        Copied!
```

**Comment by Ben8t** [comment]
@owaismultani we revamped scripting capabilities in Kestra. You can find a new detailed documentation [here](https://kestra.io/docs/developer-guide/scripts#runners).
